FROM ubuntu:18.04

COPY sources.list /etc/apt/sources.list
COPY pip.conf /root/.pip/pip.conf

RUN apt-get update && apt-get install -yq --no-install-recommends \ 
	python3.8 python3-pip libgomp1 libgl1-mesa-glx libglib2.0-dev && \
	rm /usr/bin/python3 && \
	rm /usr/bin/pip && \
	ln -s /usr/bin/python3.8 /usr/bin/python && \
	ln -s /usr/bin/python3.8 /usr/bin/python3 && \
	ln -s /usr/bin/pip3 /usr/bin/pip && \
	pip install -U pip && \
	pip install --no-cache-dir \
                torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html && \
	pip install --no-cache-dir \
		paddlepaddle==2.3.2 && \
	pip install --no-cache-dir \
		opencv-python==4.6.0.66 pymupdf==1.18.14 pandas==1.5.2 && \
	pip install --no-cache-dir \ 
		flasgger==0.9.4 -i https://pypi.douban.com/simple && \
	pip install --no-cache-dir \
		requests==2.28.1 tqdm==4.63.1 matplotlib==3.6.2 seaborn==0.11.2 && \
	pip install --no-cache-dir \
		shapely pyclipper scikit-image==0.19.3 imgaug==0.4.0 lmdb==1.3.0 && \
	pip install --no-cache-dir \
		fuzzywuzzy==0.18.0 gunicorn==20.1.0 gevent==22.10.2 && \
	apt-get autoclean && \
	rm -rf /home/* && \
	rm -rf /var/lib/apt/lists/*
