FROM ubuntu:18.04

COPY sources.list /etc/apt/sources.list
COPY pip.conf /root/.pip/pip.conf

RUN apt-get update && apt-get install -yq --no-install-recommends \ 
	python3.8 python3-pip libgomp1 libgl1-mesa-glx libglib2.0-dev && \
	rm /usr/bin/python3 && \
	rm /usr/bin/pip && \
	ln -s /usr/bin/python3.8 /usr/bin/python && \
	ln -s /usr/bin/python3.8 /usr/bin/python3 && \
	ln -s /usr/bin/pip3 /usr/bin/pip && \
	pip install -U pip && \
	# pip install --no-cache-dir \
	# 	paddlepaddle opencv-python flasgger imgaug pyclipper && \
	apt-get autoclean && \
	rm -rf /home/* && \
	rm -rf /var/lib/apt/lists/*
